Repository Emmanuel-Melon/planet-of-the-bugs, pull requests merged in 2023-03, with the labels that each got.

#15 [BUG-3]: Init Apollo GraphQL Client
  .gitignore
  package.json
  src/apollo.ts
  src/core/editor/CodeEditor.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  yarn.lock
Labels: enhancement

#16 Added Courses
  package-lock.json
  src/routes/+page.svelte
  src/routes/styles.css
  yarn.lock
Labels: good first issue

#27 [BUG-14]: Configure apollo globally
  src/lib/apollo.ts
  src/lib/queries/courses.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
Labels: enhancement, 🚀 ready for review

#23 [BUG-8]: Course Details Page
  src/components/StartCourseButton.svelte
  src/lib/mutations/courses.ts
  src/lib/queries/courses.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/Header.svelte
  src/routes/courses/+page.svelte
  src/routes/courses/[slug]/+page.svelte
  src/routes/courses/[slug]/+page.ts
Labels: enhancement, 🚀 ready for review

#32 [BUG-11] Join Course
  src/components/CourseCard.svelte
  src/components/StartCourseButton.svelte
  src/lib/mutations/courses.ts
  src/lib/queries/courses.ts
  src/routes/+page.svelte
  src/routes/courses/+page.svelte
  src/routes/courses/[slug]/+page.svelte
  src/routes/courses/[slug]/+page.ts
  src/routes/styles.css
Labels: enhancement

#34 [BUG-17]
  src/components/CourseCard.svelte
  src/routes/courses/+page.svelte
  src/routes/courses/[slug]/+page.svelte
  svelte.config.js
  tsconfig.json
Labels: enhancement, 🚀 ready for review

#33 [BUG-16]: Setup auth
  package.json
  src/hooks.server.ts
  src/routes/+layout.server.ts
  src/routes/+page.svelte
  src/routes/auth/+new-user.svelte
  yarn.lock
Labels: enhancement

#51 [BUG-23]: Install & Configure Monaco Editor
  package.json
  src/components/CodeEditor/CodeEditor.svelte
  src/components/CodeEditor/CodeOutput.svelte
  src/routes/+layout.svelte
  src/routes/courses/[slug]/[lesson]/+page.svelte
  yarn.lock
Labels: frontend, 🚀 ready for review

#37 [BUG-18] New User Welcoming Page
  .husky/pre-commit
  package.json
  src/lib/mutations/users.ts
  src/routes/auth/new-user/+page.svelte
  yarn.lock
Labels: enhancement, frontend, 🚀 ready for review
