Repository Emmanuel-Melon/planet-of-the-bugs, pull requests merged in 2023-07, with the labels that each got.

#108 Managed Subscribed Repo Page
  apps/client/src/components/Modals/ManageReposTopicsModal.svelte
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/lib/graphql/mutations/repositories.ts
  apps/client/src/lib/graphql/queries/repositories.ts
  apps/client/src/routes/repositories/+page.svelte
  apps/client/src/routes/repositories/+page.ts
  apps/client/src/routes/repositories/[id]/+page.svelte
  apps/client/src/routes/repositories/[owner]/[repoName]/+page.svelte
  apps/client/src/routes/repositories/[owner]/[repoName]/+page.ts
  apps/client/src/routes/repositories/subscribedRepos.ts
  packages/svelte-ui/components/Button.svelte
  packages/svelte-ui/components/Card.svelte
Labels: 😌 Enhancement, 🚧 WIP, 🖥️ Frontend

#119 Component Events & Event Forwarding Implementation
  apps/client/codegen.js
  apps/client/src/components/Chapters/ManageChapterDetails.svelte
  apps/client/src/components/Courses/ManageCourseDetails.svelte
  apps/client/src/components/Lessons/ManageLessonDetails.svelte
  apps/client/src/components/Modals/ManageReposTopicsModal.svelte
  apps/client/src/components/Modals/NewChapterModal.svelte
  apps/client/src/components/Modals/NewCourseModal.svelte
  apps/client/src/components/Modals/NewLessonModal.svelte
  apps/client/src/components/Repositories/OwnedRepositories.svelte
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/components/Repositories/RepositoryRecommendations.svelte
  apps/client/src/components/Settings/AccountSettings.svelte
  apps/client/src/components/StartCourseButton.svelte
  apps/client/src/components/User/UserProfileCard.svelte
  apps/client/src/routes/auth/+page.svelte
  apps/client/src/routes/auth/new-user/+page.svelte
  apps/client/src/routes/authored/+page.svelte
  apps/client/src/routes/bugs/+page.svelte
  packages/svelte-ui/Types.ts
  packages/svelte-ui/components/Button.svelte
Labels: 😌 Enhancement, 🚧 WIP, 🖥️ Frontend

#140 [BUG-63]: Implement pagination for courses page
  apps/client/src/components/Chapters/ChapterOverview.svelte
  apps/client/src/components/Chat/.ConversationMenu.svelte.icloud
  apps/client/src/components/Chat/.actions.ts.icloud
  apps/client/src/components/Chat/ConversationMenu.svelte
  apps/client/src/components/Chat/actions.ts
  apps/client/src/components/CourseCard.svelte
  apps/client/src/components/Courses/CoursesList.svelte
  apps/client/src/components/Lessons/LessonTextContent.svelte
  apps/client/src/lib/graphql/queries/courses.ts
  apps/client/src/lib/images/empty.png
  apps/client/src/routes/bugs/+page.svelte
  apps/client/src/routes/courses/+page.svelte
  apps/client/src/routes/courses/[slug]/+page.svelte
Labels: 😌 Enhancement, 🚧 WIP, 🖥️ Frontend, 🎛️ Backend

#137 Course Pages Improvements
  apps/client/src/components/Lessons/LessonInteracticeContent.svelte
  apps/client/src/components/Lessons/LessonInteractiveContent.svelte
  apps/client/src/components/Lessons/LessonOutline.svelte
  apps/client/src/components/Lessons/LessonTextContent.svelte
  apps/client/src/components/StartCourseButton.svelte
  apps/client/src/hooks.server.ts
  apps/client/src/lib/data/courses.ts
  apps/client/src/lib/data/messages.ts
  apps/client/src/lib/data/notifications.ts
  apps/client/src/lib/data/user.ts
  apps/client/src/lib/graphql/mutations/courses.ts
  apps/client/src/lib/graphql/queries/courses.ts
  apps/client/src/lib/graphql/queries/issues.ts
  apps/client/src/lib/graphql/queries/lessons.ts
  apps/client/src/lib/graphql/queries/messages.ts
  apps/client/src/lib/graphql/queries/notifications.ts
  apps/client/src/lib/graphql/queries/pullRequests.ts
  apps/client/src/lib/graphql/queries/repositories.ts
  apps/client/src/lib/graphql/queries/user.ts
  apps/client/src/routes/Header.svelte
  apps/client/src/routes/[username]/+page.server.ts
  apps/client/src/routes/authored/+page.ts
  apps/client/src/routes/bugs/+page.server.ts
  apps/client/src/routes/courses/+page.svelte
  apps/client/src/routes/courses/[slug]/+layout.server.ts
  apps/client/src/routes/courses/[slug]/+page.svelte
  apps/client/src/routes/courses/[slug]/+page.ts
  apps/client/src/routes/courses/[slug]/[id]/+layout.svelte
  apps/client/src/routes/courses/[slug]/[id]/+page.svelte
  apps/client/src/routes/courses/[slug]/[id]/+page.ts
  apps/client/src/routes/courses/[slug]/[id]/navigationStore.ts
  apps/client/src/routes/messages/+page.server.ts
  apps/client/src/routes/repositories/+page.ts
  apps/client/src/routes/styles.css
  apps/client/tailwind.config.cjs
  packages/svelte-ui/components/NextPrev.svelte
Labels: 😌 Enhancement, 🖥️ Frontend, 🚀 ready for review
