Repository Emmanuel-Melon/planet-of-the-bugs, pull requests merged in 2023-06, with the labels that each got.

#78 Appwrite Storage Crud
  apps/client/package.json
  apps/client/src/lib/appwrite/appwriteClient.ts
  apps/client/src/lib/graphql/queries/courses.ts
  apps/client/src/routes/authored/[slug]/+page.svelte
  apps/client/src/routes/authored/[slug]/+page.ts
  apps/client/src/routes/authored/helpers.ts
Labels: 🚧 WIP, 🖥️ Frontend, 🎛️ Backend, 🏗️ Architecture

#81 UI Improvements
  apps/client/src/components/AuthoredCourseCard.svelte
  apps/client/src/components/Chat/ChatInput.svelte
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/components/User/UserProfileCard.svelte
  apps/client/src/routes/+error.svelte
  apps/client/src/routes/Header.svelte
  apps/client/src/routes/auth/new-user/+page.svelte
  apps/client/src/routes/authored/+page.svelte
  apps/client/src/routes/bugs/+page.svelte
  apps/client/src/routes/bugs/+page.ts
  apps/client/src/routes/messages/+page.svelte
  apps/client/src/routes/messages/+page.ts
  apps/client/src/routes/profile/+page.svelte
  apps/client/src/routes/repositories/+page.svelte
  apps/client/src/routes/repositories/+page.ts
  apps/client/src/routes/settings/+page.svelte
  apps/client/src/routes/styles.css
Labels: 😌 Enhancement, 🖥️ Frontend, 🚀 ready for review

#84 Lessons improvements
  apps/client/package.json
  apps/client/src/components/CodeEditor/CodeEditor.svelte
  apps/client/src/components/CodeEditor/CodeOutput.svelte
  apps/client/src/components/CodeEditor/EditorIFrame.svelte
  apps/client/src/components/CodeEditor/EditorTerminal.svelte
  apps/client/src/components/CourseCard.svelte
  apps/client/src/components/Courses/NewChapterModal.svelte
  apps/client/src/components/Courses/NewCourseModal.svelte
  apps/client/src/components/Lessons/ChapterOverview.svelte
  apps/client/src/components/Lessons/LessonOutline.svelte
  apps/client/src/components/Lessons/LessonOverview.svelte
  apps/client/src/components/Lessons/LessonSidebar.svelte
  apps/client/src/components/Repositories/OwnedRepositories.svelte
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/components/SidebarFilter.svelte
  apps/client/src/components/StartCourseButton.svelte
  apps/client/src/components/User/UserGithubStats.svelte
  apps/client/src/components/User/UserProfileCard.svelte
  apps/client/src/hooks.server.ts
  apps/client/src/lib/graphql/helpers.ts
  apps/client/src/lib/graphql/mutations/courses.ts
  apps/client/src/lib/graphql/queries/courses.ts
  apps/client/src/lib/graphql/queries/lessons.ts
  apps/client/src/lib/monaco/config.ts
  apps/client/src/lib/monaco/helpers.ts
  apps/client/src/lib/monaco/init.ts
  apps/client/src/routes/+layout.svelte
  apps/client/src/routes/Header.svelte
  apps/client/src/routes/authored/+page.svelte
  apps/client/src/routes/authored/+page.ts
  apps/client/src/routes/authored/[slug]/+page.svelte
  apps/client/src/routes/authored/[slug]/+page.ts
  apps/client/src/routes/authored/[slug]/edit/+page.svelte
  apps/client/src/routes/bugs/+page.svelte
  apps/client/src/routes/courses/+page.svelte
  apps/client/src/routes/courses/+page.ts
  apps/client/src/routes/courses/[slug]/+page.svelte
  apps/client/src/routes/courses/[slug]/[id]/+page.svelte
  apps/client/src/routes/courses/[slug]/[id]/+page.ts
  apps/client/src/routes/courses/[slug]/[lesson]/+page.svelte
  apps/client/src/routes/courses/[slug]/[lesson]/+page.ts
  apps/client/src/routes/repositories/+page.svelte
  apps/client/src/routes/resources/+page.svelte
  apps/client/src/routes/styles.css
  apps/client/src/stores/navigationState.ts
  apps/client/tailwind.config.cjs
  docker-compose.yml
  docker/Dockerfile-client
  docker/Dockerfile-website
  yarn.lock
Labels: 😌 Enhancement, 🚧 WIP, 🖥️ Frontend, 🎛️ Backend

#86 [BUG-44]: Page loading animation
  apps/client/src/components/AuthoredCourseCard.svelte
  apps/client/src/components/Lessons/ChapterOverview.svelte
  apps/client/src/components/Lessons/LessonOutline.svelte
  apps/client/src/components/Repositories/OwnedRepositories.svelte
  apps/client/src/components/Repositories/SubscrbedRepositories.svelte
  apps/client/src/components/Repositories/SubscribedRepositories.svelte
  apps/client/src/components/Settings/AccountSettings.svelte
  apps/client/src/components/Settings/NotificationsSettings.svelte
  apps/client/src/components/Settings/PrivacyAndSecuritySettings.svelte
  apps/client/src/components/Settings/ProfileSettings.svelte
  apps/client/src/components/Tabs.svelte
  apps/client/src/components/User/RepositoriesContributedTo.svelte
  apps/client/src/components/User/UserGithubStats.svelte
  apps/client/src/components/User/UserPinnedItems.svelte
  apps/client/src/lib/appwrite/appwriteServer.ts
  apps/client/src/routes/+layout.svelte
  apps/client/src/routes/+page.svelte
  apps/client/src/routes/Header.svelte
  apps/client/src/routes/about/+page.svelte
  apps/client/src/routes/auth/new-user/+page.svelte
  apps/client/src/routes/courses/[slug]/+page.svelte
  apps/client/src/routes/profile/+page.svelte
  apps/client/src/routes/profile/+page.ts
  apps/client/src/routes/repositories/subscribed/+page.svelte
  apps/client/src/routes/settings/+layout.svelte
  apps/client/src/routes/settings/+page.svelte
  apps/client/src/routes/styles.css
  apps/client/tailwind.config.cjs
  packages/svelte-ui/components/Card.svelte
  packages/svelte-ui/components/MyCounterButton.svelte
  packages/svelte-ui/components/PageLoader.svelte
  packages/svelte-ui/index.ts
Labels: 😌 Enhancement, 🚧 WIP, 🖥️ Frontend

#87 Major changes to manage course UI & logic
  apps/client/src/components/Chapters/ChapterOverview.svelte
  apps/client/src/components/Chapters/ManageChapterDetails.svelte
  apps/client/src/components/Courses/ManageCourseDetails.svelte
  apps/client/src/components/Courses/NewChapterModal.svelte
  apps/client/src/components/Lessons/LessonOutline.svelte
  apps/client/src/components/Lessons/ManageLessonDetails.svelte
  apps/client/src/components/Lessons/NewLessonModal.svelte
  apps/client/src/components/ProfileTabs.svelte
  apps/client/src/lib/graphql/mutations/courses.ts
  apps/client/src/lib/graphql/mutations/lessons.ts
  apps/client/src/routes/authored/[slug]/edit/+layout.svelte
  apps/client/src/routes/authored/[slug]/edit/+layout.ts
  apps/client/src/routes/authored/[slug]/edit/+page.svelte
  apps/client/src/routes/authored/[slug]/edit/selectedTabStore.ts
  apps/client/src/routes/profile/+page.svelte
Labels: 😌 Enhancement, 🚧 WIP, 🖥️ Frontend, 🎛️ Backend

#91 Repositories & Bugs Pages Improvements
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/components/Repositories/RepositoryRecommendations.svelte
  apps/client/src/components/User/RepositoriesContributedTo.svelte
  apps/client/src/lib/graphql/queries/user.ts
  apps/client/src/routes/+page.svelte
  apps/client/src/routes/bugs/+page.svelte
  apps/client/src/routes/repositories/+page.svelte
  apps/client/src/routes/repositories/+page.ts
  apps/client/src/routes/repositories/[id]/+page.svelte
  packages/svelte-ui/components/Pagination.svelte
Labels: 🖥️ Frontend, 🚀 ready for review

#92 Improved Custom Button Component
  apps/client/src/components/Chapters/ManageChapterDetails.svelte
  apps/client/src/components/Courses/ManageCourseDetails.svelte
  apps/client/src/components/Courses/NewChapterModal.svelte
  apps/client/src/components/Courses/NewCourseModal.svelte
  apps/client/src/components/Lessons/ManageLessonDetails.svelte
  apps/client/src/components/Lessons/NewLessonModal.svelte
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/components/StartCourseButton.svelte
  apps/client/src/routes/bugs/+page.svelte
  packages/svelte-ui/components/Button.svelte
Labels: 😌 Enhancement, 🖥️ Frontend, 🚀 ready for review

#93 UI-Refactors
  apps/client/src/components/CourseCard.svelte
  apps/client/src/components/Courses/NewChapterModal.svelte
  apps/client/src/components/Courses/NewCourseModal.svelte
  apps/client/src/components/Lessons/NewLessonModal.svelte
  apps/client/src/components/Repositories/ManageRepoSubscription.svelte
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/routes/bugs/+page.svelte
  packages/svelte-ui/components/Modal.svelte
Labels: 😌 Enhancement, 🖥️ Frontend, 🚀 ready for review

#96 Dynamic profile pages
  apps/client/src/components/Chapters/ManageChapterDetails.svelte
  apps/client/src/components/Chat/ChatInput.svelte
  apps/client/src/components/Chat/ConversationMenu.svelte
  apps/client/src/components/CodeEditor/EditorTerminal.svelte
  apps/client/src/components/CourseCard.svelte
  apps/client/src/components/Footer.svelte
  apps/client/src/components/Lessons/LessonSidebar.svelte
  apps/client/src/components/Lessons/ManageLessonDetails.svelte
  apps/client/src/components/Modals/InviteFriendModal.svelte
  apps/client/src/components/Modals/NewChapterModal.svelte
  apps/client/src/components/Modals/NewConversationModal.svelte
  apps/client/src/components/Modals/NewCourseModal.svelte
  apps/client/src/components/Modals/NewLessonModal.svelte
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/components/Repositories/RepositoryRecommendations.svelte
  apps/client/src/components/Repositories/SubscribedRepositories.svelte
  apps/client/src/components/SearchBar.svelte
  apps/client/src/components/Settings/NotificationsSettings.svelte
  apps/client/src/components/Settings/ProfileSettings.svelte
  apps/client/src/components/SidebarFilter.svelte
  apps/client/src/components/User/UserGithubStats.svelte
  apps/client/src/components/User/UserPinnedItems.svelte
  apps/client/src/components/User/UserProfileCard.svelte
  apps/client/src/components/User/UserProfileCardControls.svelte
  apps/client/src/hooks.server.ts
  apps/client/src/lib/graphql/queries/repositories.ts
  apps/client/src/lib/graphql/queries/user.ts
  apps/client/src/lib/images/avatar.png
  apps/client/src/routes/Header.svelte
  apps/client/src/routes/[username]/+error.svelte
  apps/client/src/routes/[username]/+layout.server.ts
  apps/client/src/routes/[username]/+layout.svelte
  apps/client/src/routes/[username]/+page.svelte
  apps/client/src/routes/[username]/+page.ts
  apps/client/src/routes/authored/+page.svelte
  apps/client/src/routes/bugs/+page.svelte
  apps/client/src/routes/courses/+page.svelte
  apps/client/src/routes/messages/+page.svelte
  apps/client/src/routes/notifications/+page.svelte
  apps/client/src/routes/profile/+layout.svelte
  apps/client/src/routes/profile/+page.svelte
  apps/client/src/routes/repositories/+page.svelte
  apps/client/src/routes/resources/+page.svelte
  apps/client/src/routes/settings/+layout.svelte
  apps/client/tailwind.config.cjs
  packages/svelte-ui/components/Card.svelte
  packages/svelte-ui/components/Modal.svelte
  packages/svelte-ui/components/PageHeader.svelte
  yarn.lock
Labels: 😌 Enhancement, 🖥️ Frontend, 🚀 ready for review

#106 Pre-Alpha Refactor
  .circleci/config.yml
  .gitmodules
  README.md
  apps/client/src/components/AuthoredCourseCard.svelte
  apps/client/src/components/ChoicesPanes.svelte
  apps/client/src/components/CourseCard.svelte
  apps/client/src/components/Repositories/OwnedRepositories.svelte
  apps/client/src/components/Repositories/RepoOverviewCard.svelte
  apps/client/src/components/Settings/AccountSettings.svelte
  apps/client/src/components/Settings/ProfileSettings.svelte
  apps/client/src/components/User/RepositoriesContributedTo.svelte
  apps/client/src/components/User/UserGithubStats.svelte
  apps/client/src/components/User/UserPinnedItems.svelte
  apps/client/src/lib/graphql/queries/user.ts
  apps/client/src/routes/+error.svelte
  apps/client/src/routes/+page.svelte
  apps/client/src/routes/Header.svelte
  apps/client/src/routes/[username]/+error.svelte
  apps/client/src/routes/[username]/+page.ts
  apps/client/src/routes/auth/+page.svelte
  apps/client/src/routes/authored/+page.ts
  apps/client/src/routes/authored/[slug]/+page.svelte
  apps/client/src/routes/authored/[slug]/edit/+layout.svelte
  apps/client/src/routes/bugs/+page.svelte
  apps/client/src/routes/courses/+page.svelte
  apps/client/src/routes/notifications/+page.svelte
  apps/client/tailwind.config.cjs
  packages/svelte-ui/components/Card.svelte
  packages/svelte-ui/components/Dropdown.svelte
  scripts/1password/1password.sh
Labels: 🐞 Bug, 😌 Enhancement, 🖥️ Frontend, 🚀 ready for review

#107 Dynamic Repo topics
  apps/client/src/components/Modals/ManageReposTopicsModal.svelte
  apps/client/src/components/Repositories/RepositoryRecommendations.svelte
  apps/client/src/hooks.server.ts
  apps/client/src/lib/auth/BugsClientCustomAdapter.ts
  apps/client/src/lib/graphql/mutations/users.ts
  apps/client/src/lib/graphql/queries/repositories.ts
  apps/client/src/lib/graphql/queries/user.ts
  apps/client/src/routes/[username]/+layout.server.ts
  apps/client/src/routes/[username]/+page.ts
  apps/client/src/routes/authored/+page.ts
  apps/client/src/routes/repositories/+page.svelte
  apps/client/src/routes/repositories/+page.ts
  packages/bugs-lib/StringifyTopics.ts
  packages/bugs-lib/index.ts
  packages/svelte-ui/components/Button.svelte
Labels: 😌 Enhancement, 🚧 WIP, 🖥️ Frontend, 🎛️ Backend
